# Generated by Django 3.1.5 on 2021-08-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210725_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('days', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
