# Generated by Django 3.1.5 on 2021-08-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_register',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
